<?php
/**
 * Created by PhpStorm.
 * User: abdujabbor
 * Date: 7/18/18
 * Time: 3:20 PM
 */

namespace Atom\Tests;

use Atom\Http\Factory\UriFactory;
use Atom\Http\Message\Request;
use PHPUnit\Framework\TestCase;

class RequestTest extends TestCase
{
    /**
     * @var $uriFactory UriFactory
     */
    protected $uriFactory;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->uriFactory = new UriFactory();
    }

    public function testMethods()
    {
        $uri = $this->uriFactory->createUri("http://localhost:8000");
        $request = new Request("get", $uri);
        $this->assertEquals(true, $request->isGet());

        $request = new Request("post", $uri);
        $this->assertEquals(false, $request->isGet());

        $request = new Request("options", $uri);
        $this->assertEquals(true, $request->isOptions());
    }

    public function testHeaders() {
        $headers = ['Content-Type' => 'application/json'];
        $uri = $this->uriFactory->createUri("http://localhost:8000");

        $request = new Request("get", $uri, null, $headers);

        $this->assertEquals(array_merge($headers, ["Host" => ["localhost:8000"]]), $request->getHeaders());

        $this->assertEquals('application/json', $request->getHeader('Content-Type'));

    }
}
